# Generated by Django 3.1.1 on 2020-11-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_remota', '0008_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='arq',
        ),
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='file',
            name='timestamp',
        ),
    ]
